spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blood_donation_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: sendon
    password: sendon
    driver-class-name: org.mariadb.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        format_sql: true
  
  application:
    name: blood-donation-backend

server:
  port: 8080


jwt:
  secret: 12345678901234567890123456789012
  expiration: 86400000




logging:
  level:
    com.blooddonation: DEBUG
    org.springframework.security: DEBUG